services:
  todo-postgres:
    image: 'postgres:17.0-alpine'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - api_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  todo-api:
    build:
      context: ./todo-api
    restart: always
    depends_on:
      todo-postgres:
        condition: service_healthy

    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - api_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/readiness"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

volumes:
  postgres-data:

networks:
  api_db:
