services:
  todo-mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - api_db
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s


  app:
    build:
      context: ./todo-api
    restart: always
    depends_on:
      todo-mariadb:
        condition: service_healthy

    env_file:
      - .env
    ports:
      - "8002:8000"
    networks:
      - api_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/readiness"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

volumes:
  mariadb_data:

networks:
  api_db:
